#include <stdio.h>
#include <stdint.h>

/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, 
the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

*/


int main(int argc, char** argv) {

	uint64_t result = 0;
	uint64_t a = 1;
	uint64_t b = 0;
	uint64_t t = 0;
	while( a+b < 4*1000*1000 ) {
		t = a + b;
		a = b;
		b = t;
		if( b % 2 == 0 ) {
			result += b;
		}
	}



	printf("Problem 002: %llu\n", result);
}